// Answer key for Cambridge IELTS 20, Academic Test 2. Server-side only.
//
// Typed answers: an array of accepted spellings (compared case-insensitively).
// Letter / judgement answers: a single string.
// "Choose TWO" pairs: keyed "a-b", the accepted letters in any order,
// one mark per correct letter.

export const KEY = {
  listening: {
    1: ['break'],
    2: ['time'],
    3: ['shower'],
    4: ['money'],
    5: ['memory'],
    6: ['lifting'],
    7: ['fall'],
    8: ['taxi'],
    9: ['insurance'],
    10: ['stress'],
    11: 'D',
    12: 'I',
    13: 'H',
    14: 'E',
    15: 'A',
    16: 'B',
    17: 'B',
    18: 'A',
    19: 'B',
    20: 'A',
    21: 'D',
    22: 'G',
    23: 'B',
    24: 'A',
    25: 'E',
    26: 'C',
    27: 'A',
    28: 'A',
    29: 'B',
    30: 'C',
    31: ['photos', 'photographs', 'pictures'],
    32: ['vegan'],
    33: ['chefs', 'cooks'],
    34: ['journalists', 'reporters'],
    35: ['health'],
    36: ['coffee'],
    37: ['environment'],
    38: ['reputation'],
    39: ['price', 'cost'],
    40: ['soil'],
  },
  reading: {
    1: ['tail'],
    2: ['flippers'],
    3: ['hair', 'hairs'],
    4: ['seagrasses', 'seagrass'],
    5: ['lips'],
    6: ['buoyancy'],
    7: 'TRUE',
    8: 'NOT GIVEN',
    9: 'FALSE',
    10: 'NOT GIVEN',
    11: 'TRUE',
    12: 'NOT GIVEN',
    13: 'TRUE',
    14: 'B',
    15: 'F',
    16: 'B',
    17: ['laziness'],
    18: ['anxious'],
    19: ['threats'],
    20: ['exams'],
    21: ['perfectionists'],
    22: ['guilt'],
    '23-24': ['A', 'C'],
    '25-26': ['A', 'E'],
    27: 'NO',
    28: 'YES',
    29: 'NOT GIVEN',
    30: 'NO',
    31: 'NOT GIVEN',
    32: 'YES',
    33: 'F',
    34: 'D',
    35: 'H',
    36: 'B',
    37: 'G',
    38: 'B',
    39: 'D',
    40: 'C',
  },
};
